#!/usr/bin/env python3
"""
Import photos from access_photo_mappings.json to PostgreSQL

This script:
1. Reads access_photo_mappings.json (rirekisho_id → photo base64)
2. Updates candidates.photo_data_url in PostgreSQL
3. Reports statistics

Usage:
    python scripts/import_photos_from_json.py

Requirements:
    - access_photo_mappings.json must exist at /app/access_photo_mappings.json
    - PostgreSQL must be running with candidates table populated
"""

import sys
import json
from pathlib import Path
from datetime import datetime

sys.path.insert(0, '/app')

from app.core.database import SessionLocal
from app.models.models import Candidate

def import_photos_from_json():
    """Import photos from JSON mapping file"""

    json_file = Path('/app/access_photo_mappings.json')

    print("""
╔════════════════════════════════════════════════════════════╗
║          IMPORTING PHOTOS FROM JSON MAPPING                ║
╚════════════════════════════════════════════════════════════╝
""")

    # Check if JSON file exists
    if not json_file.exists():
        print(f"""
❌ ERROR: access_photo_mappings.json NOT FOUND

Expected location: {json_file}

This file should have been generated by:
- scripts/BUSCAR_FOTOS_AUTO.bat (Windows)
- backend/scripts/auto_extract_photos_from_databasejp.py

Please:
1. Run BUSCAR_FOTOS_AUTO.bat to generate the JSON file
   OR
2. Copy it manually to the container:
   docker cp access_photo_mappings.json uns-claudejp-backend:/app/

3. Run this script again

════════════════════════════════════════════════════════════

NOTA: El sistema funciona perfectamente SIN fotos.
      Este paso es opcional.

════════════════════════════════════════════════════════════
""")
        return False

    # Read JSON mapping
    print(f"📂 Reading JSON file: {json_file}")
    try:
        with open(json_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            # Extract mappings from the data structure
            photo_mappings = data.get('mappings', {}) if isinstance(data, dict) else data
    except json.JSONDecodeError as e:
        print(f"""
❌ ERROR: Invalid JSON format

Error: {str(e)}

The file might be corrupted. Please regenerate it using
BUSCAR_FOTOS_AUTO.bat
""")
        return False
    except Exception as e:
        print(f"❌ ERROR reading JSON: {str(e)}")
        return False

    print(f"✓ Loaded {len(photo_mappings):,} photo mappings")

    # Show sample
    if photo_mappings:
        sample_id = list(photo_mappings.keys())[0]
        sample_data = photo_mappings[sample_id]
        data_preview = sample_data[:50] + "..." if len(sample_data) > 50 else sample_data
        print(f"  Sample: {sample_id} → {data_preview}")
    print()

    # Connect to database
    print("📊 Connecting to PostgreSQL...")
    db = SessionLocal()

    try:
        # Get all candidates
        candidates = db.query(Candidate).all()
        total_candidates = len(candidates)
        print(f"✓ Found {total_candidates:,} candidates in database\n")

        if total_candidates == 0:
            print("""
⚠️  WARNING: No candidates found in database

Please ensure that candidates have been imported first using:
- import_candidates_improved.py

Then run this script again.
""")
            return False

        # Import photos
        print("=" * 60)
        print("  IMPORTING PHOTOS TO POSTGRESQL")
        print("=" * 60)
        print()

        updated = 0
        skipped = 0
        errors = 0
        start_time = datetime.now()

        for candidate in candidates:
            rirekisho_id = str(candidate.rirekisho_id)

            if rirekisho_id in photo_mappings:
                try:
                    photo_data = photo_mappings[rirekisho_id]

                    # Validate photo data format
                    if not isinstance(photo_data, str):
                        print(f"  ⚠️  Invalid data type for {rirekisho_id}: {type(photo_data)}")
                        errors += 1
                        continue

                    if not photo_data.startswith('data:image/'):
                        print(f"  ⚠️  Invalid photo format for {rirekisho_id}")
                        print(f"      Expected: data:image/...")
                        print(f"      Got: {photo_data[:30]}...")
                        errors += 1
                        continue

                    # Update candidate
                    candidate.photo_data_url = photo_data
                    db.commit()
                    updated += 1

                    # Progress indicator every 100 photos
                    if updated % 100 == 0:
                        elapsed = (datetime.now() - start_time).total_seconds()
                        rate = updated / elapsed if elapsed > 0 else 0
                        remaining = (total_candidates - updated) / rate if rate > 0 else 0
                        print(f"  ✓ {updated:,}/{total_candidates:,} photos imported "
                              f"({updated/total_candidates*100:.1f}%) "
                              f"- {rate:.1f} photos/sec "
                              f"- ETA: {int(remaining)}s")

                except Exception as e:
                    db.rollback()
                    print(f"  ❌ Error for rirekisho_id {rirekisho_id}: {str(e)[:50]}")
                    errors += 1
            else:
                skipped += 1

        # Final stats
        elapsed = (datetime.now() - start_time).total_seconds()

        print()
        print("=" * 60)
        print("  IMPORT COMPLETED")
        print("=" * 60)
        print()
        print(f"📊 Summary:")
        print(f"  ✓ Photos imported:     {updated:,}")
        print(f"  ⚠️  Skipped (no photo):  {skipped:,}")
        print(f"  ❌ Errors:             {errors:,}")
        print(f"  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        print(f"  📈 Total candidates:   {total_candidates:,}")
        print(f"  📸 Coverage:           {updated/total_candidates*100:.1f}%")
        print(f"  ⏱️  Time elapsed:       {int(elapsed)}s ({elapsed/60:.1f} minutes)")
        if updated > 0:
            print(f"  ⚡ Import rate:        {updated/elapsed:.1f} photos/sec")
        print()

        if errors > 0:
            print("⚠️  WARNING: Some photos failed to import")
            print("   Check the error messages above for details")
            print()

        if skipped > 0:
            print(f"ℹ️  INFO: {skipped:,} candidates without photos in mapping")
            print("   This is normal if not all candidates have photos")
            print()

        if updated > 0:
            print("✅ Photos successfully imported to PostgreSQL!")
            print()
            print("   Verify in database:")
            print("   SELECT COUNT(*) FROM candidates WHERE photo_data_url IS NOT NULL;")
            print(f"   Expected result: {updated:,}")
            print()

        return True

    except Exception as e:
        print(f"""
╔════════════════════════════════════════════════════════════╗
║          ERROR DURING IMPORT                               ║
╚════════════════════════════════════════════════════════════╝

Error: {str(e)}

Stack trace:
""")
        import traceback
        traceback.print_exc()
        return False

    finally:
        db.close()

if __name__ == '__main__':
    print("""
╔════════════════════════════════════════════════════════════╗
║    UNS-ClaudeJP 5.2 - Photo Import from JSON              ║
╚════════════════════════════════════════════════════════════╝
""")

    success = import_photos_from_json()

    if success:
        print("""
╔════════════════════════════════════════════════════════════╗
║    ✅ IMPORT SUCCESSFUL                                    ║
╚════════════════════════════════════════════════════════════╝
""")
        sys.exit(0)
    else:
        print("""
╔════════════════════════════════════════════════════════════╗
║    ⚠️  IMPORT FAILED OR SKIPPED                            ║
╚════════════════════════════════════════════════════════════╝

El sistema funciona perfectamente sin fotos.
Las fotos se pueden agregar manualmente después.
""")
        sys.exit(1)
