"""add pays_parking field to apartment_assignments

Revision ID: 43b6cf501eed
Revises: 642bced75435
Create Date: 2025-11-12 10:31:29.762756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43b6cf501eed'
down_revision: Union[str, None] = '642bced75435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_assignments', sa.Column('pays_parking', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment_assignments', 'pays_parking')
    # ### end Alembic commands ###
