"""Add apartment system v2 - assignments charges deductions

Revision ID: 5e6575b9bf1b
Revises: 001
Create Date: 2025-11-11 09:21:32.804970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6575b9bf1b'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add name column as nullable first
    op.add_column('apartments', sa.Column('name', sa.String(length=200), nullable=True))
    # Step 2: Populate name from apartment_code for existing records
    op.execute("UPDATE apartments SET name = apartment_code WHERE name IS NULL")
    # Step 3: Now make it NOT NULL
    op.alter_column('apartments', 'name', nullable=False)
    op.add_column('apartments', sa.Column('building_name', sa.String(length=200), nullable=True))
    op.add_column('apartments', sa.Column('room_number', sa.String(length=20), nullable=True))
    op.add_column('apartments', sa.Column('floor_number', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('postal_code', sa.String(length=10), nullable=True))
    op.add_column('apartments', sa.Column('prefecture', sa.String(length=50), nullable=True))
    op.add_column('apartments', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('apartments', sa.Column('address_line1', sa.String(length=200), nullable=True))
    op.add_column('apartments', sa.Column('address_line2', sa.String(length=200), nullable=True))
    op.add_column('apartments', sa.Column('room_type', sa.Enum('ONE_K', 'ONE_DK', 'ONE_LDK', 'TWO_K', 'TWO_DK', 'TWO_LDK', 'THREE_LDK', 'STUDIO', 'OTHER', name='room_type'), nullable=True))
    op.add_column('apartments', sa.Column('size_sqm', sa.Numeric(precision=6, scale=2), nullable=True))
    # Add base_rent as nullable first, then populate from monthly_rent
    op.add_column('apartments', sa.Column('base_rent', sa.Integer(), nullable=True))
    op.execute("UPDATE apartments SET base_rent = monthly_rent WHERE base_rent IS NULL")
    op.alter_column('apartments', 'base_rent', nullable=False)
    op.add_column('apartments', sa.Column('management_fee', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('deposit', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('key_money', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('default_cleaning_fee', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('contract_start_date', sa.Date(), nullable=True))
    op.add_column('apartments', sa.Column('contract_end_date', sa.Date(), nullable=True))
    op.add_column('apartments', sa.Column('landlord_name', sa.String(length=200), nullable=True))
    op.add_column('apartments', sa.Column('landlord_contact', sa.String(length=200), nullable=True))
    op.add_column('apartments', sa.Column('real_estate_agency', sa.String(length=200), nullable=True))
    op.add_column('apartments', sa.Column('emergency_contact', sa.String(length=200), nullable=True))
    op.add_column('apartments', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'RESERVED', name='apartment_status'), nullable=True))
    op.add_column('apartments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('apartments', 'apartment_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('apartments', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('apartments', 'monthly_rent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_apartments_name'), 'apartments', ['name'], unique=False)
    op.create_unique_constraint('uq_assignment_year_month', 'rent_deductions', ['assignment_id', 'year', 'month'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_assignment_year_month', 'rent_deductions', type_='unique')
    op.drop_index(op.f('ix_apartments_name'), table_name='apartments')
    op.alter_column('apartments', 'monthly_rent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('apartments', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('apartments', 'apartment_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('apartments', 'updated_at')
    op.drop_column('apartments', 'status')
    op.drop_column('apartments', 'emergency_contact')
    op.drop_column('apartments', 'real_estate_agency')
    op.drop_column('apartments', 'landlord_contact')
    op.drop_column('apartments', 'landlord_name')
    op.drop_column('apartments', 'contract_end_date')
    op.drop_column('apartments', 'contract_start_date')
    op.drop_column('apartments', 'default_cleaning_fee')
    op.drop_column('apartments', 'key_money')
    op.drop_column('apartments', 'deposit')
    op.drop_column('apartments', 'management_fee')
    op.drop_column('apartments', 'base_rent')
    op.drop_column('apartments', 'size_sqm')
    op.drop_column('apartments', 'room_type')
    op.drop_column('apartments', 'address_line2')
    op.drop_column('apartments', 'address_line1')
    op.drop_column('apartments', 'city')
    op.drop_column('apartments', 'prefecture')
    op.drop_column('apartments', 'postal_code')
    op.drop_column('apartments', 'floor_number')
    op.drop_column('apartments', 'room_number')
    op.drop_column('apartments', 'building_name')
    op.drop_column('apartments', 'name')
    # ### end Alembic commands ###
