"""Add additional_charges and rent_deductions tables

Revision ID: 68534af764e0
Revises: 5e6575b9bf1b
Create Date: 2025-11-11 09:25:10.826770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68534af764e0'
down_revision: Union[str, None] = '5e6575b9bf1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
